### ISSUE TITLE
    trailblazer-loader (0.0.6)     trailblazer-rails (0.2.3)

### ISSUE THREAD

**Issue by amalagaura** [apotonick/trailblazer#103]
I have a Rails app. The docs say I can run `collection` in a controller method

My Gemfile.lock has
```
    rails (4.2.5)
    trailblazer-loader (0.0.6)
    trailblazer-rails (0.2.3)
    trailblazer (1.1.0)
```

But when I run collection `Group::Index.present(params)` in my collection method:

```
class PermitsController < ApplicationController
  def show
    collection Group::Index.present(params)
  end
end
```

 I get:

```
undefined method `collection' for #<PermitsController:0x007faca0aa31c0>
```

It works with the `op = Group::Index.present(params)` fine

**Comment by apotonick** [comment]
Hey Ankur,

the `collection` method is not documented and will be removed at some point, since you can do exactly the same with `present` (as you already found out yourself :stuck_out_tongue_winking_eye: ). Since the term _"model"_ doesn't have to refer to a single object necessarily, but could also be a collection, this is just fine.

**Comment by amalagaura** [comment]
Oh looks like I did not `include Trailblazer::Operation::Controller`. That `collection` was the first thing I tried.

**Comment by apotonick** [comment]
That's odd, because `trailblazer-rails` automatically includes this into `ApplicationController`. I've had problems with that in development mode with auto-reload, though.
