### ISSUE TITLE
respond_with is gone as of Rails 4.2.0

### ISSUE THREAD

**Issue by spectator** [apotonick/trailblazer#24]
You probably aware of this, but in case you don't
https://github.com/rails/rails/blob/4-2-0/guides/source/4_2_release_notes.md#respond_with--class-level-respond_to

Trailblazer might need different approach or have responders as a dependency.

**Comment by apotonick** [comment]
As discussed in #25, the long-term plan is to introduce an `Endpoint` layer in Trailblazer that replicates the responder logic without the controller dependencies. This will help using Trb operations in other frameworks like Sinatra or Lotus.

Until we get to that, we can simply use the `responders` gem.

**Comment by spectator** [comment]
Sounds good :)

**Comment by fernandes** [comment]
about this issue, I added gem `responders` as a development dependency on https://github.com/apotonick/trailblazer/pull/36 so can make rails tests pass

@apotonick do you think its necessary to add some alert if not using `responders`? I think we don't need because `responders` only will be a dependency if use `respond` on a controller.

@spectator @apotonick can we close this issue atm?

**Comment by spectator** [comment]
@fernandes fine by me

**Comment by fernandes** [comment]
@spectator :+1:

**Comment by apotonick** [comment]
Let's simply add `responders` for now, in a separate PR please. We can make it optional, etc. when we have `Endpoint`. I mean, we're still 0.2 :wink:

**Comment by fernandes** [comment]
I added just as development dep on https://github.com/apotonick/trailblazer/pull/36/ and just require on [test_helper.rb](https://github.com/apotonick/trailblazer/pull/36/files#diff-4d056a69f9b152dea0ffdac967d5a403R2) so I think its ok... tests are passing and user handles `responders` on its own application
