### ISSUE TITLE
Namespaced routes in operations

### ISSUE THREAD

**Issue by paulofabiano** [apotonick/trailblazer#37]
Hi, Guys! 

I'm not sure yet if this is a real issue but I'm going to report it anyway.

I have an application with a namespace:

```ruby
namespace :admin do
    resources :users
end
```

This is my Admin::UsersController:

```ruby
class Admin::UsersController < ApplicationController
    include Trailblazer::Operation::Controller
    def create

		run User::Create do |op|
			return redirect_to op.model
		end

		render action: :new

	end
end
```

And my Operation:

```ruby
class User < ActiveRecord::Base

	class Create < Trailblazer::Operation

		include CRUD
		include ActiveModel

		model User, :create

		contract do
			...
		end

		def process(params)
			validate(params[:user]) do |f|
				f.save
			end
		end

	end
end
```

This is my test for the #create action in that controller:

```ruby
it 'posts successfully' do
	post :create, {user: attributes_for(:user)}
	expect(response).to redirect_to(user_path(User.last))
end
```

When I run this test, I get the following error:
Admin::UsersController#create posts successfully
     Failure/Error: post :create, {user: attributes_for(:user)}
     NoMethodError:
       undefined method `user_url' for #<Admin::UsersController:0x007f8ee0ee54a0>

Maybe because of rails convention, trailblazer is struggling with the routes. Is that correct of maybe it is some implementation error from my side?

**Comment by paulofabiano** [comment]
@fernandes could you help me with that, please?

**Comment by fernandes** [comment]
instead of:

```ruby
run User::Create do |op|
  return redirect_to op.model
end
render action: :new
```

could you please try with:

```ruby
respond User::Create
```

Tell if it worked, if not I need to check whats happening, was supposed to work with redirect like [here](https://github.com/apotonick/gemgem-trbrb/blob/master/app/controllers/things_controller.rb#L9-13) in gemgem-trbrb

btw, what trailblazer version are you using?

**Comment by paulofabiano** [comment]
Hi, @fernandes!

So, I'm using 0.2.2.

And it didn't work:

1) Admin::UsersController#create posts successfully
     Failure/Error: post :create, {user: attributes_for(:user)}
     NameError:
       uninitialized constant Admin::UsersController::Create

**Comment by paulofabiano** [comment]
@fernandes I changed

```ruby
 return redirect_to op.model
```
to
```ruby
 return redirect_to admin_user_path(op.model)
```
and now it is working.

**Comment by fernandes** [comment]
uow, great its working right now...

So probably it's a problem how Trailblazer is working with namespace, I'm gonna leave it opened so I can check later how how better with namespace. I have some idea but would like to check better first.

thank you

**Comment by paulofabiano** [comment]
Great :)
I'll try to learn more about trailblazer source codes to be able to contribute more active, once we are implement a brand new project here from the ground with trailblazer, so we are facing lot's of interesting things.

**Comment by fernandes** [comment]
sounds great... :)

**Comment by apotonick** [comment]
I don't think this is a problem with Trailblazer - we really just return the model instance. The real problem is how Rails handles namespaces in combination with URL helpers.

My idea is to change URL helpers in Rails. This is actually why I started Trailblazer in the first place hahahaha :laughing: !

Instead of magically guessing namespaces (look at Rails' implementation) the controller will know its namespace and provide a URL helper instance that in turns knows the namespace. No more guessing.

It will look like this.

```ruby
run User::Create do |op|
  return redirect_to op.model
end
```

And then `#redirect_to` might work as follows.

```ruby
def redirect_to(model)
  super url_to(model)
```

Where `url_to` knows the namespace (it's a controller method) and the model.

**Comment by fernandes** [comment]
Configuration over Convention uahauhauahu :D

But using with railsblocks I had no problem with all this stuff... but its ok, now we know how to handle this case :wink:

**Comment by paulofabiano** [comment]
Thanks guys! :)
