### ISSUE TITLE
Operations without Model howto ?

### ISSUE THREAD

**Issue by elbouillon** [apotonick/trailblazer#42]
Hi,

First of all, thanks! I discovered your book and new way to organise rails project only 2 weeks ago, but I totally agree with yours ideas.

I red the written part of your book (sadly where there is nothing about non crud operations).

To start, I chosen to implement Trailblazer way for my search "concept", actually it's a simple controller with an index method and everythings inthere (I know, really bad...)

I created a new concept, with an operation file : app/concepts/search/operation.rb, and a class 

    class Ppl::Search
      class Create < Trailblazer::Operation
        contract do
          property :q
        end

        def process(params)
          self
        end
      end
    end

Nothing complex, but I've 2 problem I can't get through : 

1. This is not autoloaded (because not named crud, as I found in trailblazer source https://github.com/apotonick/trailblazer/blob/master/lib/trailblazer/rails/railtie.rb#L4
2. What I understand reading the book was that an operation always return [res, op], but It's only when we use a contract and validate that we get op back, shouldn't you mention that in your book ?

Hope this is not a stupid question, regards and nice easter week-end!

**Comment by elbouillon** [comment]
I'm using rails 3.2

**Comment by apotonick** [comment]
Hi Mikael,

yeah the `crud.rb` autoloading is an attempt to establish a convention. I had the idea to make this configurable, so that other files can be added. 

```ruby
config do
  autoload_files << "operations"
end
```

... or something like that.

You can also name the file `app/concepts/ppl/search/create.rb` if you want Ruby's autoloading to hit (I know, that sucks).

The operation returns what you return in `#process`. This will be discussed in the next chapter where we talk about non-CRUD operations. Thanks for your valuable input, bro!!!
